### ISSUE TITLE
Unexpected error fetching senec data: Unterminated string starting at: line 1 column 1004 (char 1003)

### ISSUE THREAD

**Issue by JoJa1101** [mchwalisz/home-assistant-senec#13]
Sometimes I'm getting this error:

> 2021-10-20 00:37:31 ERROR (MainThread) [custom_components.senec] Unexpected error fetching senec data: Unterminated string starting at: line 1 column 1004 (char 1003)
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
> self.data = await self._async_update_data()
> File "/config/custom_components/senec/__init__.py", line 69, in _async_update_data
> await self.senec.update()
> File "/usr/local/lib/python3.9/site-packages/pysenec/__init__.py", line 87, in update
> await self.read_senec_v21()
> File "/usr/local/lib/python3.9/site-packages/pysenec/__init__.py", line 119, in read_senec_v21
> self._raw = parse(await res.json())
> File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1113, in json
> return loads(stripped.decode(encoding))
> File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
> return _default_decoder.decode(s)
> File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
> obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1004 (char 1003)

Any idea why this happens?

**Comment by mchwalisz** [comment]
Do you have this often?

It kind of looks like you got incomplete/wrong response from the device. Are you sure your address is correct?

**Comment by mchwalisz** [comment]
Interesting, is your device on Wi-Fi? I expect there is some communication problem happening.

Anyway, the integration shouldn't crash in that case. I will look into catching that exception and reacting accordingly.

**Comment by JoJa1101** [comment]
Thanks a lot.
I run only UniFi network devices and the SENEC Home battery is in a different VLAN then Home Assistant. Maybe this could also be a reason?

**Comment by JoJa1101** [comment]
Issue doesnt happen anymore since last FW Updates.
