### ISSUE TITLE
Mismatch between data from senec portal and data from the integration

### ISSUE THREAD

**Issue by h4nnes** [mchwalisz/home-assistant-senec#22]
Hi, is the mismatch normal? E.g. The integratation is displaying a total amounf of 9035 kWh for the senec solar generated. in the senec web portal is displaying 8820 kWh?

**Comment by mchwalisz** [comment]
The integration itself doesn't generate the data it asks local device. I'd suggest asking senec itself for that.

I actually expect that senec web portal started collecting data for you as an user some time after the device was installed, so the starting point is different and that's the reason for a mismatch.

Currently I do not expect it to be an integration problem
