### ISSUE TITLE
No date during battery diags

### ISSUE THREAD

**Issue by loeffelpan** [mchwalisz/home-assistant-senec#28]
After remote shutdown has ended - at least in my case - senec annouced that there will be ongoing battery adjustments.
I noticed that there is a phase of one or two hours every morning (first time battery starts charging) where my devices shows "battery diagnosis" on the display.

During that time home assistant gets no data from senec. Unfortunately that ruins the stats/graphs on the energy dashboard. Any way to work around this? Data in the senec app is fine.

**Comment by neubi4** [comment]
The reason for this is the same as in #26 
It is already fixed in the underlying python lib mchwalisz/pysenec#7 but at the moment there is no new release with this fix.

We asked mchwalisz in #26 to create a new release and are waiting for the response.

**Comment by loeffelpan** [comment]
Ah, sorry for dupe then.
I will subscribe #26 and close this.
