### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by rey90** [mchwalisz/home-assistant-senec#4]
Hello

i have tryied to install / configure the plugin. But when i install it via HACS or coping to the filesystem they arent any promts. For the IP / PW /...

Could you please post a exampe config 

Thanks

**Comment by mchwalisz** [comment]
Have you tried setting up new integration via web interface? 

i.e. Configuration > Integrations> Set up a new integration.

**Comment by rey90** [comment]
i think i have tried it yesterday and the plugin didn´t appear. however after a few restarts the plugin is no vissible and the dialog is shown. Sorry and thanks
