### ISSUE TITLE
Total connection loss

### ISSUE THREAD

**Issue by caladrien** [mchwalisz/home-assistant-senec#49]
Hi,

Used this integration very good for long time. I guess since the last update to 2023.8 i cannot connect anymore. 

Log saying:
`Logger: custom_components.senec.config_flow
Source: custom_components/senec/config_flow.py:63
Integration: senec (documentation, issues)
First occurred: 13:03:31 (4 occurrences)
Last logged: 13:04:33

Could not connect to Senec device at 192.168.178.7, check host ip address`

This log is after a complete reinstall of the hacs integration. 

What I've done so far:
- deleting config of my senec through UI
- reconfiger over add integration with "connection faild" as a result
- rebooted the main router
- perfectly reachable over web browser with that given IP adress.

**Comment by marq24** [comment]
what you missed to do is to search for similar issues ;-) - please see #47

Duplicate of #47

**Comment by caladrien** [comment]
> what you missed to do is to search for similar issues ;-) - please see #47
> 
> Duplicate of #47

Search a couple of them. 

Should it such major change isn't part of a in HACS available updates or even in the beta channel, shouldn't it? If i understand senec correct every battery received this update.

Problem solved with #47
