### ISSUE TITLE
Constant Name changed for VOLT in Home Assistant core-2021.8.0

### ISSUE THREAD

**Issue by Dntouch** [mchwalisz/home-assistant-senec#7]
Constant names changed with latest Home Assistant core Version. 

[https://github.com/home-assistant/core/pull/53243](https://github.com/home-assistant/core/pull/53243)

Rename VOLT to ELECTRIC_POTENTIAL_VOLT in const.py

**Comment by mchwalisz** [comment]
Should be closed after the merge, reopen if necessary.
